export const dashboardPage = String.raw`<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Ruby Upgrade Workspace</title>
<style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#101114;color:#e9e9ed;font:15px ui-sans-serif,system-ui,-apple-system,sans-serif;line-height:1.45}main{max-width:1080px;margin:auto;padding:56px 28px 90px}h1{font-size:34px;letter-spacing:-.7px;margin:0 0 7px}h2{font-size:20px;margin:12px 0 4px}.sub,small{color:#a8acb7}.card{background:#191b20;border:1px solid #30333b;border-radius:12px;padding:20px;margin:15px 0;box-shadow:0 8px 30px #0002}.tag{display:inline-block;background:#302028;color:#ffb7ba;border-radius:99px;padding:4px 9px;font-size:12px;margin-right:6px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(135px,1fr));gap:10px;margin:16px 0}.metric{background:#121419;border-radius:9px;padding:10px}.metric b{display:block;color:#fff;font-size:17px;overflow-wrap:anywhere}.iteration{border-top:1px solid #30333b;margin-top:16px;padding-top:14px}ul{padding-left:21px;margin:9px 0}pre{white-space:pre-wrap;color:#c9ccd4;font:13px ui-monospace,SFMono-Regular,monospace}a{color:#ff9da1}code{background:#252831;padding:2px 4px;border-radius:4px}
</style></head><body><main><h1>Ruby Upgrade Workspace</h1><p class="sub">Local-only migration evidence, test health, and source citations.</p><div id="app"></div></main><script>
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl=value=>/^https?:\/\//.test(String(value))?esc(value):'#';
const metric=(label,value)=>'<div class="metric"><small>'+esc(label)+'</small><b>'+esc(value??'—')+'</b></div>';
const testValue=(tests,key,fallback='—')=>tests&&tests[key]!==undefined&&tests[key]!==null?tests[key]:fallback;
fetch('/api/runs').then(response=>response.json()).then(runs=>{
 const app=document.querySelector('#app');
 if(!runs.length){app.innerHTML='<article class="card"><b>No upgrade runs yet.</b><p>Run <code>/ruby-upgrade</code> from a linked Git worktree. Evidence will appear under <code>.ruby-upgrades/runs/</code>.</p></article>';return;}
 app.innerHTML=runs.map(run=>{const iterations=run.iterations||[];const latest=iterations.at(-1)||{};const tests=latest.tests||{};const commits=(run.localCommits||[]).map(sha=>'<code>'+esc(sha)+'</code>').join(' ')||'No local commit found yet.';const target=run.reportType==='rails_bridge'?'Rails '+(run.targetRails||'target unknown'):'Ruby '+(run.targetRuby||'target unknown');const bridge=run.reportType==='rails_bridge'?'<p><b>Blocked Ruby hop:</b> '+esc(run.bridge?.rubyFrom)+' → '+esc(run.bridge?.rubyTo)+' · <code>'+esc(run.bridge?.rubyReportPath)+'</code></p>':'';const details=iterations.map(iteration=>{const itTests=iteration.tests||{};const fixes=(iteration.fixes||[]).map(fix=>'<li><b>'+esc((fix.files||[]).join(', ')||'Migration fix')+'</b><br>'+esc(fix.explanation)+'</li>').join('')||'<li>No code or dependency fixes recorded.</li>';const citations=(iteration.citations||[]).map(citation=>'<a href="'+safeUrl(citation.url)+'" target="_blank" rel="noreferrer">'+esc(citation.title||citation.url)+'</a>').join(' · ')||'No citations recorded.';const appUpdate=iteration.appUpdateReview?'<small>app:update: '+esc(iteration.appUpdateReview.outcome)+' — '+esc(iteration.appUpdateReview.summary)+'</small>':'';return '<section class="iteration"><b>'+esc(iteration.from)+' → '+esc(iteration.to)+' · '+esc(iteration.status)+'</b><div class="grid">'+metric('Test result',itTests.passed===true?'Passed':itTests.passed===false?'Failed':'—')+metric('Smoke check',testValue(itTests,'smoke'))+metric('Coverage',testValue(itTests,'coveragePercent',null)===null?'—':testValue(itTests,'coveragePercent')+'%')+'</div><ul>'+fixes+'</ul>'+appUpdate+'<br><small>Sources: '+citations+'</small></section>';}).join('');return '<article class="card"><span class="tag">'+esc(run.status||'unknown')+'</span><span class="tag">'+esc(target)+'</span><h2>'+esc(run.title||run.file)+'</h2><p class="sub">'+esc(run.startedAt||'Unknown start')+' · '+esc(run.branch||'Unknown branch')+'</p><div class="grid">'+metric('Tests',testValue(tests,'count'))+metric('Coverage',testValue(tests,'coveragePercent',null)===null?'—':testValue(tests,'coveragePercent')+'%')+metric('Duration',testValue(tests,'durationSeconds',null)===null?'—':testValue(tests,'durationSeconds')+'s')+metric('Smoke check',testValue(tests,'smoke'))+'</div><pre>'+esc((run.summary||[]).join('\n'))+'</pre>'+bridge+details+'<p><b>Local commits:</b> '+commits+'</p><p><b>Session:</b> '+esc(run.sessionSummary||'—')+'</p></article>';}).join('');
}).catch(error=>{document.querySelector('#app').innerHTML='<article class="card">Could not load upgrade reports: '+esc(error.message)+'</article>';});
</script></body></html>`;
